server:
  port: 8761

eureka:
  instance:
    hostname: eurekaserver1
    appname: eureka-cluster
  environment: local
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka
    register-with-eureka: true
    fetch-registry: true