server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true

#    Oauth credentials
  security:
    oauth2:
      client:
        registration:
          google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope:
                - email
                - profile
              redirect-uri: "{baseUrl}/oauth2/callback/google"

jwt:
 secret: YXNlY3VyZVJBTkRPTWtleWZvcnNlY3JldFNpZ25pbmdlYXN5c3RvY2hhbmdl
 access-token-expiration: 3600000 # 1 hour
 refresh-token-expiration: 86400000 # 24 hours

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.authservice: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
