version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: walletuser
      MYSQL_PASSWORD: walletpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=walletuser
      - SPRING_DATASOURCE_PASSWORD=walletpass
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - backend

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/wallet_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=walletuser
      - SPRING_DATASOURCE_PASSWORD=walletpass
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - backend

  api-gateway:
    build: ./qr-cloud-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - wallet-service
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data: