spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        # Auth Service Route
        - id: authModule
          uri: http://localhost:8084
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/auth

        # Wallet Service Route
        - id: walletModule
          uri: http://localhost:8081
          predicates:
            - Path=/api/wallets/**
          filters:
            - RewritePath=/api/wallets/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/wallets

server:
  port: 8080


# Debug Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.web.reactive: DEBUG